/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateIncidentArgs } from "./CreateIncidentArgs";
import { UpdateIncidentArgs } from "./UpdateIncidentArgs";
import { DeleteIncidentArgs } from "./DeleteIncidentArgs";
import { IncidentFindManyArgs } from "./IncidentFindManyArgs";
import { IncidentFindUniqueArgs } from "./IncidentFindUniqueArgs";
import { Incident } from "./Incident";
import { User } from "../../user/base/User";
import { IncidentService } from "../incident.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Incident)
export class IncidentResolverBase {
  constructor(
    protected readonly service: IncidentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Incident",
    action: "read",
    possession: "any",
  })
  async _incidentsMeta(
    @graphql.Args() args: IncidentFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Incident])
  @nestAccessControl.UseRoles({
    resource: "Incident",
    action: "read",
    possession: "any",
  })
  async incidents(
    @graphql.Args() args: IncidentFindManyArgs
  ): Promise<Incident[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Incident, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Incident",
    action: "read",
    possession: "own",
  })
  async incident(
    @graphql.Args() args: IncidentFindUniqueArgs
  ): Promise<Incident | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Incident)
  @nestAccessControl.UseRoles({
    resource: "Incident",
    action: "create",
    possession: "any",
  })
  async createIncident(
    @graphql.Args() args: CreateIncidentArgs
  ): Promise<Incident> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        userId: args.data.userId
          ? {
              connect: args.data.userId,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Incident)
  @nestAccessControl.UseRoles({
    resource: "Incident",
    action: "update",
    possession: "any",
  })
  async updateIncident(
    @graphql.Args() args: UpdateIncidentArgs
  ): Promise<Incident | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          userId: args.data.userId
            ? {
                connect: args.data.userId,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Incident)
  @nestAccessControl.UseRoles({
    resource: "Incident",
    action: "delete",
    possession: "any",
  })
  async deleteIncident(
    @graphql.Args() args: DeleteIncidentArgs
  ): Promise<Incident | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async userId(@graphql.Parent() parent: Incident): Promise<User | null> {
    const result = await this.service.getUserId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
